export interface Plant {
  id: string;
  name: string;
  emoji: string;
  color: string;
  spacing: number; // inches
  sunNeeds: 'full-sun' | 'partial-sun' | 'shade';
  daysToMaturity: number;
  startIndoorsWeeks: number; // weeks before last frost
  transplantWeeks: number; // weeks after last frost
  companions: string[]; // plant IDs that grow well together
  antagonists: string[]; // plant IDs to avoid
  category: 'vegetable' | 'herb' | 'fruit';
}

export const plants: Plant[] = [
  // Vegetables
  {
    id: 'tomato',
    name: 'Tomato',
    emoji: '🍅',
    color: '#e74c3c',
    spacing: 24,
    sunNeeds: 'full-sun',
    daysToMaturity: 80,
    startIndoorsWeeks: 6,
    transplantWeeks: 2,
    companions: ['basil', 'carrot', 'onion', 'parsley'],
    antagonists: ['cabbage', 'fennel', 'potato', 'kohlrabi'],
    category: 'vegetable',
  },
  {
    id: 'pepper',
    name: 'Bell Pepper',
    emoji: '🫑',
    color: '#f39c12',
    spacing: 18,
    sunNeeds: 'full-sun',
    daysToMaturity: 70,
    startIndoorsWeeks: 8,
    transplantWeeks: 2,
    companions: ['basil', 'onion', 'carrot', 'tomato'],
    antagonists: ['fennel', 'kohlrabi', 'bean'],
    category: 'vegetable',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    emoji: '🥬',
    color: '#2ecc71',
    spacing: 8,
    sunNeeds: 'partial-sun',
    daysToMaturity: 45,
    startIndoorsWeeks: 4,
    transplantWeeks: 0,
    companions: ['carrot', 'radish', 'strawberry', 'basil', 'onion'],
    antagonists: ['celery', 'parsley'],
    category: 'vegetable',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    emoji: '🥕',
    color: '#e67e22',
    spacing: 3,
    sunNeeds: 'full-sun',
    daysToMaturity: 70,
    startIndoorsWeeks: 0,
    transplantWeeks: 0, // direct sow
    companions: ['tomato', 'lettuce', 'onion', 'rosemary', 'sage'],
    antagonists: ['dill', 'celery'],
    category: 'vegetable',
  },
  {
    id: 'onion',
    name: 'Onion',
    emoji: '🧅',
    color: '#9b59b6',
    spacing: 4,
    sunNeeds: 'full-sun',
    daysToMaturity: 100,
    startIndoorsWeeks: 8,
    transplantWeeks: 2,
    companions: ['tomato', 'pepper', 'carrot', 'lettuce', 'cabbage'],
    antagonists: ['bean', 'pea', 'sage'],
    category: 'vegetable',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    emoji: '🥗',
    color: '#27ae60',
    spacing: 18,
    sunNeeds: 'full-sun',
    daysToMaturity: 80,
    startIndoorsWeeks: 6,
    transplantWeeks: 2,
    companions: ['onion', 'celery', 'potato', 'dill'],
    antagonists: ['tomato', 'strawberry', 'grape'],
    category: 'vegetable',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    emoji: '🥒',
    color: '#16a085',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 55,
    startIndoorsWeeks: 3,
    transplantWeeks: 1,
    companions: ['bean', 'corn', 'pea', 'radish', 'sunflower'],
    antagonists: ['potato', 'sage', 'melon'],
    category: 'vegetable',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    emoji: '🥒',
    color: '#2d5a27',
    spacing: 24,
    sunNeeds: 'full-sun',
    daysToMaturity: 50,
    startIndoorsWeeks: 3,
    transplantWeeks: 1,
    companions: ['corn', 'bean', 'radish', 'marigold'],
    antagonists: ['potato', 'pumpkin'],
    category: 'vegetable',
  },
  {
    id: 'bean',
    name: 'Green Bean',
    emoji: '🫘',
    color: '#228b22',
    spacing: 4,
    sunNeeds: 'full-sun',
    daysToMaturity: 55,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['corn', 'cucumber', 'carrot', 'cabbage', 'potato'],
    antagonists: ['onion', 'garlic', 'pepper', 'fennel'],
    category: 'vegetable',
  },
  {
    id: 'corn',
    name: 'Corn',
    emoji: '🌽',
    color: '#f1c40f',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 80,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['bean', 'cucumber', 'squash', 'pumpkin'],
    antagonists: ['tomato', 'celery'],
    category: 'vegetable',
  },
  {
    id: 'radish',
    name: 'Radish',
    emoji: '🔴',
    color: '#dc143c',
    spacing: 2,
    sunNeeds: 'full-sun',
    daysToMaturity: 25,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['lettuce', 'pea', 'cucumber', 'bean', 'carrot'],
    antagonists: ['cabbage', 'hyssop'],
    category: 'vegetable',
  },
  {
    id: 'potato',
    name: 'Potato',
    emoji: '🥔',
    color: '#8b4513',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 90,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['bean', 'corn', 'cabbage', 'horseradish'],
    antagonists: ['tomato', 'cucumber', 'squash', 'sunflower'],
    category: 'vegetable',
  },
  // Herbs
  {
    id: 'basil',
    name: 'Basil',
    emoji: '🌿',
    color: '#27ae60',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 30,
    startIndoorsWeeks: 6,
    transplantWeeks: 1,
    companions: ['tomato', 'pepper', 'lettuce', 'oregano'],
    antagonists: ['sage', 'rue'],
    category: 'herb',
  },
  {
    id: 'cilantro',
    name: 'Cilantro',
    emoji: '🌱',
    color: '#20bf6b',
    spacing: 4,
    sunNeeds: 'partial-sun',
    daysToMaturity: 25,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['tomato', 'spinach', 'bean', 'pepper'],
    antagonists: ['fennel', 'lavender'],
    category: 'herb',
  },
  {
    id: 'parsley',
    name: 'Parsley',
    emoji: '🌿',
    color: '#26de81',
    spacing: 6,
    sunNeeds: 'partial-sun',
    daysToMaturity: 70,
    startIndoorsWeeks: 8,
    transplantWeeks: 2,
    companions: ['tomato', 'asparagus', 'carrot', 'chive'],
    antagonists: ['lettuce', 'mint'],
    category: 'herb',
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    emoji: '🌿',
    color: '#4a7c59',
    spacing: 24,
    sunNeeds: 'full-sun',
    daysToMaturity: 365,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['bean', 'cabbage', 'carrot', 'sage'],
    antagonists: ['cucumber', 'pumpkin'],
    category: 'herb',
  },
  {
    id: 'mint',
    name: 'Mint',
    emoji: '🌿',
    color: '#00b894',
    spacing: 18,
    sunNeeds: 'partial-sun',
    daysToMaturity: 90,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['cabbage', 'tomato', 'pea'],
    antagonists: ['parsley', 'chamomile'],
    category: 'herb',
  },
  // Fruits
  {
    id: 'strawberry',
    name: 'Strawberry',
    emoji: '🍓',
    color: '#e74c3c',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 365,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['lettuce', 'spinach', 'onion', 'thyme'],
    antagonists: ['cabbage', 'broccoli'],
    category: 'fruit',
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    emoji: '🍉',
    color: '#ff6b6b',
    spacing: 36,
    sunNeeds: 'full-sun',
    daysToMaturity: 85,
    startIndoorsWeeks: 3,
    transplantWeeks: 2,
    companions: ['corn', 'radish', 'bean', 'marigold'],
    antagonists: ['potato', 'cucumber'],
    category: 'fruit',
  },
  // More vegetables
  {
    id: 'spinach',
    name: 'Spinach',
    emoji: '🥬',
    color: '#1e8449',
    spacing: 4,
    sunNeeds: 'partial-sun',
    daysToMaturity: 40,
    startIndoorsWeeks: 4,
    transplantWeeks: 0,
    companions: ['strawberry', 'pea', 'bean', 'cabbage', 'cauliflower'],
    antagonists: [],
    category: 'vegetable',
  },
  {
    id: 'kale',
    name: 'Kale',
    emoji: '🥬',
    color: '#145a32',
    spacing: 18,
    sunNeeds: 'partial-sun',
    daysToMaturity: 55,
    startIndoorsWeeks: 4,
    transplantWeeks: 1,
    companions: ['beet', 'celery', 'cucumber', 'onion', 'potato'],
    antagonists: ['strawberry', 'tomato'],
    category: 'vegetable',
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    emoji: '🥦',
    color: '#229954',
    spacing: 18,
    sunNeeds: 'full-sun',
    daysToMaturity: 70,
    startIndoorsWeeks: 6,
    transplantWeeks: 2,
    companions: ['beet', 'celery', 'cucumber', 'onion', 'potato', 'oregano'],
    antagonists: ['strawberry', 'tomato', 'pepper'],
    category: 'vegetable',
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    emoji: '🥬',
    color: '#d5f5e3',
    spacing: 18,
    sunNeeds: 'full-sun',
    daysToMaturity: 75,
    startIndoorsWeeks: 6,
    transplantWeeks: 2,
    companions: ['bean', 'celery', 'onion', 'spinach'],
    antagonists: ['tomato', 'strawberry'],
    category: 'vegetable',
  },
  {
    id: 'pea',
    name: 'Peas',
    emoji: '🟢',
    color: '#7dcea0',
    spacing: 3,
    sunNeeds: 'full-sun',
    daysToMaturity: 60,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['carrot', 'corn', 'cucumber', 'radish', 'spinach', 'turnip'],
    antagonists: ['onion', 'garlic', 'potato'],
    category: 'vegetable',
  },
  {
    id: 'squash',
    name: 'Butternut Squash',
    emoji: '🎃',
    color: '#d68910',
    spacing: 24,
    sunNeeds: 'full-sun',
    daysToMaturity: 100,
    startIndoorsWeeks: 3,
    transplantWeeks: 1,
    companions: ['corn', 'bean', 'radish', 'marigold'],
    antagonists: ['potato'],
    category: 'vegetable',
  },
  {
    id: 'beet',
    name: 'Beet',
    emoji: '🟣',
    color: '#943126',
    spacing: 4,
    sunNeeds: 'full-sun',
    daysToMaturity: 55,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['broccoli', 'cabbage', 'lettuce', 'onion', 'garlic'],
    antagonists: ['bean', 'mustard'],
    category: 'vegetable',
  },
  {
    id: 'celery',
    name: 'Celery',
    emoji: '🥬',
    color: '#a9dfbf',
    spacing: 8,
    sunNeeds: 'partial-sun',
    daysToMaturity: 120,
    startIndoorsWeeks: 8,
    transplantWeeks: 2,
    companions: ['bean', 'cabbage', 'tomato', 'cauliflower', 'leek'],
    antagonists: ['carrot', 'parsley', 'corn'],
    category: 'vegetable',
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    emoji: '🌱',
    color: '#52be80',
    spacing: 18,
    sunNeeds: 'full-sun',
    daysToMaturity: 730,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['tomato', 'parsley', 'basil', 'carrot'],
    antagonists: ['onion', 'garlic', 'potato'],
    category: 'vegetable',
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    emoji: '🍆',
    color: '#6c3483',
    spacing: 24,
    sunNeeds: 'full-sun',
    daysToMaturity: 75,
    startIndoorsWeeks: 8,
    transplantWeeks: 2,
    companions: ['bean', 'pepper', 'spinach', 'thyme', 'marigold'],
    antagonists: ['fennel'],
    category: 'vegetable',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    emoji: '🧄',
    color: '#ecf0f1',
    spacing: 4,
    sunNeeds: 'full-sun',
    daysToMaturity: 240,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['tomato', 'pepper', 'cabbage', 'beet', 'strawberry'],
    antagonists: ['bean', 'pea', 'sage'],
    category: 'vegetable',
  },
  {
    id: 'leek',
    name: 'Leek',
    emoji: '🧅',
    color: '#aed6f1',
    spacing: 6,
    sunNeeds: 'full-sun',
    daysToMaturity: 120,
    startIndoorsWeeks: 8,
    transplantWeeks: 2,
    companions: ['carrot', 'celery', 'onion', 'strawberry'],
    antagonists: ['bean', 'pea'],
    category: 'vegetable',
  },
  // More herbs
  {
    id: 'oregano',
    name: 'Oregano',
    emoji: '🌿',
    color: '#7dcea0',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 80,
    startIndoorsWeeks: 6,
    transplantWeeks: 1,
    companions: ['tomato', 'pepper', 'basil', 'squash'],
    antagonists: [],
    category: 'herb',
  },
  {
    id: 'thyme',
    name: 'Thyme',
    emoji: '🌿',
    color: '#82e0aa',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 85,
    startIndoorsWeeks: 6,
    transplantWeeks: 1,
    companions: ['cabbage', 'strawberry', 'tomato', 'eggplant'],
    antagonists: [],
    category: 'herb',
  },
  {
    id: 'sage',
    name: 'Sage',
    emoji: '🌿',
    color: '#abebc6',
    spacing: 24,
    sunNeeds: 'full-sun',
    daysToMaturity: 75,
    startIndoorsWeeks: 6,
    transplantWeeks: 1,
    companions: ['cabbage', 'carrot', 'rosemary', 'bean'],
    antagonists: ['cucumber', 'onion', 'basil'],
    category: 'herb',
  },
  {
    id: 'dill',
    name: 'Dill',
    emoji: '🌿',
    color: '#d5f5e3',
    spacing: 12,
    sunNeeds: 'full-sun',
    daysToMaturity: 40,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['cabbage', 'lettuce', 'onion', 'cucumber'],
    antagonists: ['carrot', 'tomato', 'pepper'],
    category: 'herb',
  },
  {
    id: 'chives',
    name: 'Chives',
    emoji: '🌿',
    color: '#73c6b6',
    spacing: 6,
    sunNeeds: 'full-sun',
    daysToMaturity: 60,
    startIndoorsWeeks: 6,
    transplantWeeks: 1,
    companions: ['carrot', 'tomato', 'apple', 'grape'],
    antagonists: ['bean', 'pea'],
    category: 'herb',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    emoji: '💜',
    color: '#a29bfe',
    spacing: 18,
    sunNeeds: 'full-sun',
    daysToMaturity: 90,
    startIndoorsWeeks: 8,
    transplantWeeks: 2,
    companions: ['rosemary', 'sage', 'thyme'],
    antagonists: ['mint'],
    category: 'herb',
  },
  {
    id: 'marigold',
    name: 'Marigold',
    emoji: '🌼',
    color: '#f39c12',
    spacing: 10,
    sunNeeds: 'full-sun',
    daysToMaturity: 50,
    startIndoorsWeeks: 4,
    transplantWeeks: 1,
    companions: ['tomato', 'pepper', 'squash', 'cucumber', 'melon'],
    antagonists: ['bean', 'cabbage'],
    category: 'herb',
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    emoji: '🌻',
    color: '#f1c40f',
    spacing: 18,
    sunNeeds: 'full-sun',
    daysToMaturity: 80,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['corn', 'cucumber', 'squash', 'melon'],
    antagonists: ['potato', 'bean'],
    category: 'herb',
  },
  {
    id: 'pumpkin',
    name: 'Cantaloupe',
    emoji: '🍈',
    color: '#f5b041',
    spacing: 36,
    sunNeeds: 'full-sun',
    daysToMaturity: 85,
    startIndoorsWeeks: 3,
    transplantWeeks: 2,
    companions: ['corn', 'sunflower', 'radish', 'marigold'],
    antagonists: ['potato'],
    category: 'fruit',
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    emoji: '🫐',
    color: '#5dade2',
    spacing: 48,
    sunNeeds: 'full-sun',
    daysToMaturity: 730,
    startIndoorsWeeks: 0,
    transplantWeeks: 0,
    companions: ['strawberry', 'azalea', 'hydrangea'],
    antagonists: ['tomato', 'pepper', 'eggplant'],
    category: 'fruit',
  },
];

export const getPlantById = (id: string): Plant | undefined => {
  return plants.find(p => p.id === id);
};

export const getPlantsByCategory = (category: Plant['category']): Plant[] => {
  return plants.filter(p => p.category === category);
};

// USDA Hardiness Zone data
export const zones = [
  { zone: 3, lastFrost: 'May 15', firstFrost: 'September 15' },
  { zone: 4, lastFrost: 'May 10', firstFrost: 'September 25' },
  { zone: 5, lastFrost: 'May 1', firstFrost: 'October 5' },
  { zone: 6, lastFrost: 'April 20', firstFrost: 'October 15' },
  { zone: 7, lastFrost: 'April 10', firstFrost: 'October 25' },
  { zone: 8, lastFrost: 'March 25', firstFrost: 'November 5' },
  { zone: 9, lastFrost: 'March 1', firstFrost: 'November 15' },
  { zone: 10, lastFrost: 'February 15', firstFrost: 'November 25' },
  { zone: 11, lastFrost: 'January 15', firstFrost: 'December 15' },
];

export const getZoneData = (zone: number) => {
  return zones.find(z => z.zone === zone) || zones[4];
};
